FROM debian:stretch-slim

RUN apt-get update \
	&& apt-get install -y bsd-mailx postfix rsyslog \
	&& addgroup hostgroup \
	&& adduser --gecos 'Host User' --ingroup hostgroup --disabled-password hostuser \
	&& find /var/cache/apt /var/lib/apt -type f -delete \
	&& true

COPY rsyslog-stderr.conf /etc/rsyslog.d
COPY entrypoint-postfix /sbin/entrypoint

EXPOSE 25
ENTRYPOINT ["/sbin/entrypoint"]
CMD ["/usr/lib/postfix/sbin/master", "-d"]
